// <auto-generated />
namespace Contso.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCoursesTable_MissingJunctionAndDepartmentInCourses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCoursesTable_MissingJunctionAndDepartmentInCourses));
        
        string IMigrationMetadata.Id
        {
            get { return "201708160205108_AddCoursesTable_MissingJunctionAndDepartmentInCourses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
