// <auto-generated />
namespace Contso.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddDepartmentsTable_MissingInstructorInDepartment_1vNForeignkeysModifyNeeded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDepartmentsTable_MissingInstructorInDepartment_1vNForeignkeysModifyNeeded));
        
        string IMigrationMetadata.Id
        {
            get { return "201708160211503_AddDepartmentsTable_MissingInstructorInDepartment_1vNForeignkeysModifyNeeded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
